---
- name: 'Ensure NetworkManager is installed'
  community.general.pacman:
    name:
      - 'networkmanager'
    state: 'present'
  retries: 5

- name: 'Ensure NetworkManager PPTP support is installed'
  community.general.pacman:
    name:
      - 'networkmanager-pptp'
    state: 'present'
  retries: 5
  when: 'network_pptp'

- name: 'Ensure NetworkManager GUI applet is installed'
  community.general.pacman:
    name:
      - 'network-manager-applet'
    state: 'present'
  retries: 5
  when: 'network_gui'

- name: 'Ensure captive portal support is installed'
  community.general.pacman:
    name:
      - 'capnet-assist'
    state: 'present'
  retries: 5
  when: 'network_captive_portal'

- name: 'Ensure NetworkManager wireless connections are configured'
  ansible.builtin.template:
    src: 'nm-wifi-connection.j2'
    dest: '/etc/NetworkManager/system-connections/{{ item.SSID }}.nmconnection'
    owner: 'root'
    group: 'root'
    mode: '0600'
    force: '{{ item.overwrite | default(false, true) }}'
  loop: '{{ network_wifi_connections }}'
  notify:
    - 'restart network-manager'

- name: 'Ensure NetworkManager is enabled and started'
  ansible.builtin.systemd:
    name: 'NetworkManager.service'
    enabled: true
    state: 'started'

- name: 'Ensure NetworkManager dispatcher is enabled and started'
  ansible.builtin.systemd:
    name: 'NetworkManager-dispatcher.service'
    enabled: true
  notify:
    - 'start network-manager-dispatcher'
