---
- name: 'Install promiscuous service'
  ansible.builtin.copy:
    src: 'promiscuous@.service'
    dest: '/etc/systemd/system/promiscuous@.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: 'network_install_promiscuous_service'
